# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Super Snail
subtitle: At the bottom of the well, it is destined to see only the sky at the wellhead. 
          However, the starting point only affects the process of reaching your peak and does not determine the height you reach.
author: Dusign
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://dusign.net       # Note: don't forget to modify the CNAME file to your url
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: justcooking
email: mohamed0group@gmail.com
description: "Welcome to the world-famous Just cooking Subscribe to our channel and stay up to date on our latest pranks, Recipe tutorials, tips, techniques and the best bits from the archives."
keyword: "bacon,emt,epic meal time,sauce boss,greasiest sandwich ever,worst pizza ever
Food,Lifestyle, sociology, cook, cooking,Cookin wit AB, Smokin and Grillin wit AB, pork, 
pork chop, pork chops, fried pork chops, dinner, meat chop, fried, cooking, 
how to cook pork chops, recipe, food, pork chops recipe, chops, frying, 
meat, pork chop recipe, restaurant, bbq, barbecue, how to cook, comfort food, 
fry, beef, pig, fried pork, recipes, easy pork chop recipe, pan fried pork chops, 
pork chop recipes, how to make fried pork chops, Best Fried Pork Chops, cooking with ab, 
southern food, cooking show, kitchen, cook, southern, how to cook, how to bake, recipes, eat,
taste, byrontalbott, sweet, savory, cooking, spices, homemade, how to make, slicing, dicing, 
chef, cook, chicken, full length,nigella bites,beef (food),simply nigella,nigella lawson,
nigella kitchen,nigella lawson 2018,nigella lawson recipes,nigella lawson ribs recipe,
forever summer nigella lawson,forever summer with nigella,nigella summer forever,
nigella summer recipes,spare ribs recipe,sticky spare ribs recipe,spicy spare ribs recipe, 
Tasty,Food,Recipes,DIY,Meals,Desserts,Dinner,Breakfast,Lunch,Easy,Simply,Buzzfeed,
BuzzFeed Tasty,How To, GWR, Guinness World Records, Guinness Records, Guinness, World Record, 
Guinness Book, World Record Book, record book, record breakers, Record, Officially Amazing, 2017, 
guinness buch der rekorde, ギネス世界記録, ギネス, lo show dei record, frances quinn, bake off, 
great british bake off, jaffa cake, largest jaffa cake, largest cake, largest vegan cake, jaffa, 
cake, jaffa cakes, baking, fabrizio fasano jr, mão na massa, bake off brasil, gbbo, 
the great british bake off, ビスケット, クッキー, ケーキ, 食, デザート, cooking,yummy cooking,
cooking recipe,cooking skill,food,street food,funny,fun,english,learn english,Lifestyle,
just cooking,gordon ramsay,cooking show,marco pierre white,steak,steak recipe,GORDON RAMSAY,
gordon ramsay kitchen nightmares,gordon ramsay cooking,how to cook,MARCO PIERRE WHITE,
marco pierre white cooking,chef,education,challenge,challenges,ideas,do it yourself,
life hacks,story"
header-img: img/header_img/just cooking banner.jpeg
signature: true #show signature
signature-img: img/signature/jcooking.png

# SNS settings
twitter_username:   mohamed32950500
facebook_username:  just0cooking
instagram_username: chefcooktshirt
dailymotion_username: justcooking

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
ga_domain: yoursite

# Sidebar settings
sidebar: true                      # whether or not using Sidebar.
sidebar-about-description: "Welcome to the world-famous Just cooking Subscribe to our channel and stay up to date on our latest pranks, Recipe tutorials, tips, techniques and the best bits from the archives."
sidebar-avatar: img/myAvatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- search
- featured-tags
- short-about
- visitor
- recent-posts
- friends-blog
- archive
- category

## Search
search:
  enable: true
  path: search.xml
  field: post
  content: true

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 5              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    # {
    #     title: "Dusign's Blog",
    #     href: "https://blog.csdn.net/d_Nail"
    # },{
    #     title: "Dusign's Web",
    #     href: "#"
    # },{
    #     title: "Dusign's Github",
    #     href: "https://github.com/dusign"
    # },{
    #     title: "Other",
    #     href: "#"
    # }
]

math:
  enable: true
  engine: mathjax

#Custom Setting End

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
photography_dir: photography
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: jekyll-theme-minimal

#sitemap
sitemap:
  path: sitemap.xml
## Baidusitemap
baidusitemap:
path: baidusitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
      github: github.justcooking.mohamed0group
      coding:
  branch: master

## share
share: true

# Comment
## This comment system is gitment
## gitment url: https://github.com/imsun/gitment
comment:
  gitment:
    enable: false
    owner:
    repo:
    client_id:
    client_secret:
  livere:
    enable: false
  disqus:
    enable: false
    username:

## music
music: true

# Tip
tip:
  enable: true
  copyright: This is copyright.
  content: false

# Background effects
## If there is no effect after modification, please empty the cache and try again.
## ⚠️ The following special effects will take up a lot of cpu resorces, please open it carefully.
bg_effects:
  enable: true
  line:
    enable: false
    color: 129,200,61
    pointColor: 129,200,61
    opacity: 0.7
    zIndex: -9
    count: 99
  mouse_click:
    enable: true
    content: '"🌱","just do it","🍀"'
    color: '"rgb(121,93,179)"
          ,"rgb(76,180,231)"
          ,"rgb(184,90,154)"'
  wave:
    enable: true

# Color Theme
## light , dark or star
## If you set the value of the `color_theme` to `dark`, set the value of the `highlight_theme` to `night` in `/theme/snail/config.yml`
## `mouse_control` is only valid for star themes
color_theme: light
mouse_control: false

# Visitor statistics
visitor:
  enable: true
  type:

# Chinese Blog
chinese_blog:
  enable: true
  url: YOUR_CHINESE_BLOG_URL
